[package]
name = "fragile-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fragile"
path = "src/main.rs"

[[bin]]
name = "fragilec"
path = "src/bin/fragilec.rs"

[dependencies]
fragile-common.workspace = true
fragile-build.workspace = true
fragile-clang.workspace = true
fragile-parser-clang.workspace = true
fragile-parser-core.workspace = true
clap.workspace = true
miette.workspace = true
